// This file is auto-generated by scripts/generate-data.js.
// Do not edit directly; edit places.md instead.

export interface Place {
  name: string;
  url: string;
  category: string;
  notes?: string;
}

export interface Category {
  name: string;
  places: Place[];
}

export const categories: Category[] = [
  {
    "name": "cafes / coffee shops",
    "places": [
      {
        "name": "black sheep coffee",
        "url": "https://blacksheepcoffee.vmos.io/store/f16a9a48-e3f1-453c-8c14-90f09725d645/menu/category/740eccd0-2844-4ac8-9786-224bf663e325/bundles?menuUUID=21a7a281-1694-49e3-ab31-717707c8b774",
        "category": "cafes / coffee shops"
      },
      {
        "name": "blank street coffee",
        "url": "https://www.blankstreet.com/BlankStreetUKAllergenGuideNov22024.pdf",
        "category": "cafes / coffee shops",
        "notes": "more available on the app"
      },
      {
        "name": "cafe nero",
        "url": "https://www.caffenero.com/uk/menu",
        "category": "cafes / coffee shops"
      },
      {
        "name": "costa coffee",
        "url": "https://www.costa.co.uk/",
        "category": "cafes / coffee shops"
      },
      {
        "name": "gail's",
        "url": "https://assets.gailsbread.co.uk/wp-content/uploads/2023/02/21110658/Coffee-matrix_SUMMER.pdf",
        "category": "cafes / coffee shops"
      },
      {
        "name": "ole & steen",
        "url": "https://cdn.sanity.io/files/of2lz0sx/production/dd7989bd7cd61605e8e1d4798b71f537f4d0bc48.pdf",
        "category": "cafes / coffee shops"
      },
      {
        "name": "paul",
        "url": "https://www.paul-uk.com/",
        "category": "cafes / coffee shops",
        "notes": "more available in store"
      },
      {
        "name": "pret a manger",
        "url": "https://www.pret.co.uk/en-GB/our-menu",
        "category": "cafes / coffee shops"
      },
      {
        "name": "soho coffee co",
        "url": "https://sohocoffee.com/wp-content/uploads/2025/05/Nutritional-Matrix-Drinks-May-2025-V1.pdf",
        "category": "cafes / coffee shops"
      },
      {
        "name": "starbucks",
        "url": "https://www.starbucks.co.uk/nutrition",
        "category": "cafes / coffee shops"
      },
      {
        "name": "watch house coffee",
        "url": "https://res.cloudinary.com/watchhouse/image/upload/v1717600467/June%20Menus%202024/Exterior_Coffee_Menu_with_Rarities_-_June_-_2024_sncwjy.pdf",
        "category": "cafes / coffee shops"
      }
    ]
  },
  {
    "name": "fast food",
    "places": [
      {
        "name": "burger king",
        "url": "https://www.burgerking.co.uk/nutrition-explorer",
        "category": "fast food"
      },
      {
        "name": "dixy chicken",
        "url": "https://deliveroo.co.uk/menu/birmingham/selly-oak/dixy-chicken-selly-oak?srsltid=AfmBOoqPsesyJYXYQGcbMV3AYl4eCruPGjpUIofqisAk7Dx7SfO8izFj",
        "category": "fast food"
      },
      {
        "name": "greggs",
        "url": "https://a.storyblok.com/f/94904/x/7dd8489dab/nutritional-information.pdf",
        "category": "fast food"
      },
      {
        "name": "jollibee",
        "url": "https://static1.squarespace.com/static/5f33b417d073c907b3c2e379/t/62588146ea3f40285419c193/1649967430972/Jollibee+Calorie+Chart.pdf",
        "category": "fast food"
      },
      {
        "name": "kfc",
        "url": "https://www.kfc.co.uk/nutrition-allergens?close",
        "category": "fast food"
      },
      {
        "name": "mcdonald's",
        "url": "https://www.mcdonalds.com/gb/en-gb/menu.html",
        "category": "fast food"
      },
      {
        "name": "popeyes",
        "url": "https://popeyesuk.com/nutrition",
        "category": "fast food"
      },
      {
        "name": "slim chickens",
        "url": "https://www.slimchickens.co.uk/menus",
        "category": "fast food"
      },
      {
        "name": "subway",
        "url": "https://www.subway.com/-/media/United_Kingdom/2022/W1/Jan22NutritionalInformation.pdf",
        "category": "fast food"
      },
      {
        "name": "the halal guys",
        "url": "https://thehalalguys.com/wp-content/uploads/2021/08/Nutrition-menu-ACC.pdf",
        "category": "fast food"
      },
      {
        "name": "wendy's",
        "url": "https://www.wendys.com/en-gb/nutrition",
        "category": "fast food"
      },
      {
        "name": "wimpy",
        "url": "https://www.google.com/search?client=safari&rls=en&q=wimpy+calorie+uk&ie=UTF-8&oe=UTF-8",
        "category": "fast food"
      },
      {
        "name": "west cornwall pasty",
        "url": "https://api.westcornwallpasty.co.uk/wp-content/uploads/2025/07/WCPCo-ALL-AllergensNutritionals-Tables-080725.pdf",
        "category": "fast food"
      },
      {
        "name": "wingstop",
        "url": "https://www.wingstop.co.uk/content/wingstop-uk-allergen-info-v2.pdf",
        "category": "fast food"
      }
    ]
  },
  {
    "name": "general / others",
    "places": [
      {
        "name": "bill's restaurants",
        "url": "https://bills-website.co.uk/menus/",
        "category": "general / others"
      },
      {
        "name": "bread street kitchen",
        "url": "https://www.gordonramsayrestaurants.com/assets/1Calorie-Matrices/BSK-CALORIE-MATRIX.pdf",
        "category": "general / others",
        "notes": "gordon ramsay"
      },
      {
        "name": "hendon street kitchen",
        "url": "https://www.gordonramsayrestaurants.com/assets/Uploads/Heddon-Street-ALC-with-calories-border.pdf?srsltid=AfmBOoqEoqJSiioFmZziU0zaXhtFPXnR3t6Hy3b4etRtIT4VhEtKuAaF",
        "category": "general / others",
        "notes": "gordon ramsay"
      },
      {
        "name": "nando's",
        "url": "https://www.nandos.co.uk/food/menu/",
        "category": "general / others"
      },
      {
        "name": "san carlo gran cafe",
        "url": "https://images.selfridges.com/is/content/selfridges/content/site/pdf/PAPER22_Gran_Cafe_Manchster_(Cropped).pdf",
        "category": "general / others"
      },
      {
        "name": "the brass rail",
        "url": "https://images.selfridges.com/is/content/selfridges/content/site/pdf/BRASS_RAIL_A4_Menu_03.22.pdf",
        "category": "general / others",
        "notes": "selfriges"
      },
      {
        "name": "the ivy",
        "url": "https://viewthe.menu/dwav",
        "category": "general / others"
      }
    ]
  },
  {
    "name": "salads / sandwiches / brunches",
    "places": [
      {
        "name": "dolly's",
        "url": "https://images.selfridges.com/is/content/selfridges/content/site/pdf/Dolly_s_MENU_March_2022.pdf",
        "category": "salads / sandwiches / brunches",
        "notes": "selfriges"
      },
      {
        "name": "honi poke",
        "url": "https://www.honipoke.com/calories",
        "category": "salads / sandwiches / brunches"
      },
      {
        "name": "le pain quotidien",
        "url": "https://www.lepainquotidien.com/uk/en/menu",
        "category": "salads / sandwiches / brunches"
      },
      {
        "name": "megan's restaurants",
        "url": "https://menus.tenkites.com/megans/megans",
        "category": "salads / sandwiches / brunches"
      },
      {
        "name": "pure",
        "url": "https://order.pure.co.uk/order",
        "category": "salads / sandwiches / brunches"
      },
      {
        "name": "the salad project",
        "url": "https://assets.ctfassets.net/e84omrhhp8ey/6BfBgpwNiDNs2rDo6goq4S/2277111dc46651191eaa87912b2ab94d/Web_Allergen_Matrix_-_Q2_2025.pdf",
        "category": "salads / sandwiches / brunches"
      },
      {
        "name": "tossed",
        "url": "https://tosseduk.com/result/",
        "category": "salads / sandwiches / brunches"
      },
      {
        "name": "urban greens",
        "url": "https://www.urbangreens.co.uk/our-menu",
        "category": "salads / sandwiches / brunches"
      }
    ]
  },
  {
    "name": "sweets / desserts / snack",
    "places": [
      {
        "name": "amorino's",
        "url": "https://admin.amorino.com/wp-content/uploads/2024/12/MENU-INGREDIENTS-WEB.pdf",
        "category": "sweets / desserts / snack"
      },
      {
        "name": "auntie anne's",
        "url": "https://assets.ctfassets.net/zqt8tllj2cy0/2jjVNaTNGDoMGd4QVucpSy/0f94c0d0541ec11a334dba7ce6fc56b0/Auntie-Annes-Nutrition-Guide.pdf",
        "category": "sweets / desserts / snack"
      },
      {
        "name": "buns from home",
        "url": "https://www.bunsfromhome.com/faqs",
        "category": "sweets / desserts / snack"
      },
      {
        "name": "cinnabon",
        "url": "https://cinnabon.uk/pages/allergens-and-nutritional-information",
        "category": "sweets / desserts / snack"
      },
      {
        "name": "creams cafe",
        "url": "https://www.creamscafe.com/brochures/Allergen-Matrix--16-May-25.pdf",
        "category": "sweets / desserts / snack"
      },
      {
        "name": "crosstown",
        "url": "https://www.crosstown.co.uk/doughnuts/?_ga=2.158004792.385338914.1754161273-758837058.1754161273",
        "category": "sweets / desserts / snack"
      },
      {
        "name": "dunkin' donuts",
        "url": "https://dunkin.co.uk/allergens-donuts",
        "category": "sweets / desserts / snack"
      },
      {
        "name": "el & n",
        "url": "https://images.selfridges.com/is/content/selfridges/content/site/pdf/Elan_Menu.pdf",
        "category": "sweets / desserts / snack"
      },
      {
        "name": "heavenly desserts",
        "url": "https://heavenlydesserts.3s-pos.com/",
        "category": "sweets / desserts / snack"
      },
      {
        "name": "krispy kreme",
        "url": "https://www.krispykreme.co.uk/nutritionals?srsltid=AfmBOopxVs8KOswxQRetWQopEA0RIVQk_UGA1HhsJftyClTmpGzCJ6B1",
        "category": "sweets / desserts / snack"
      },
      {
        "name": "mr pretzel",
        "url": "https://www.google.com/search?client=safari&rls=en&q=mr+pretzel+calorie&ie=UTF-8&oe=UTF-8",
        "category": "sweets / desserts / snack"
      }
    ]
  },
  {
    "name": "american",
    "places": [
      {
        "name": "frankie & benny's",
        "url": "https://www.frankieandbennys.com/menu",
        "category": "american",
        "notes": "american-italian"
      },
      {
        "name": "tgi fridays",
        "url": "https://www.tgifridays.co.uk/menu",
        "category": "american"
      }
    ]
  },
  {
    "name": "asian",
    "places": [
      {
        "name": "banana tree",
        "url": "https://bananatree.co.uk/menu",
        "category": "asian"
      },
      {
        "name": "cafe rasa malaysia",
        "url": "https://pickup.rasa.co.uk/#most-popular",
        "category": "asian"
      },
      {
        "name": "chopstix",
        "url": "https://chopstixnoodles.co.uk/wp-content/uploads/2025/01/Nutritional-Values-V13-January-2025.pdf",
        "category": "asian"
      },
      {
        "name": "lucky cat \\- gordon ramsay",
        "url": "https://www.gordonramsayrestaurants.com/assets/1Menus-With-Calories/Lucky-Cat/Mayfair/Lucky-Cat-Mayfair-KCAL.pdf?srsltid=AfmBOoqRr2QkjDCNj2lkdraHi1vaT1lZFuMaZQsXBVeEwPO5UZfWLDQr",
        "category": "asian"
      },
      {
        "name": "wagamama",
        "url": "https://www.wagamama.com/menu?category=shareables",
        "category": "asian"
      }
    ]
  },
  {
    "name": "burger",
    "places": [
      {
        "name": "burger & lobster",
        "url": "https://www.burgerandlobster.com/locations/london/soho/menu",
        "category": "burger"
      },
      {
        "name": "byrons",
        "url": "https://allergymenu.app/menu/tri321",
        "category": "burger"
      },
      {
        "name": "five guys",
        "url": "https://fiveguys.co.uk/app/uploads/2021/07/FGUK-Nutritional-Info_-DIGITAL-V130421.pdf",
        "category": "burger"
      },
      {
        "name": "gbk (gourmet burger kitchen)",
        "url": "https://gbk.co.uk/dietary-information",
        "category": "burger"
      },
      {
        "name": "gordon ramsay \\- street burger",
        "url": "https://www.gordonramsayrestaurants.com/assets/1Calorie-Matrices/DUAL-STREET-CALORIE-MATRIX.pdf?srsltid=AfmBOop-eophm3xa36CYYN0bmXXrhXLxHKHmrTtoAmm7SS7FxhWo2i9j",
        "category": "burger"
      },
      {
        "name": "honest burgers",
        "url": "https://www.honestburgers.co.uk/wp-content/uploads/2021/02/hb_nutritionals-0221-final2.pdf",
        "category": "burger"
      },
      {
        "name": "shake shack",
        "url": "https://www.shakeshack.co.uk/wp-content/uploads/2022/10/SS_Nutritional-InformationSticky-Toffee.pdf",
        "category": "burger"
      }
    ]
  },
  {
    "name": "caribbean",
    "places": [
      {
        "name": "turtle bay",
        "url": "https://turtlebay.co.uk/assets/site/allergen-info.pdf",
        "category": "caribbean"
      }
    ]
  },
  {
    "name": "dutch",
    "places": [
      {
        "name": "my old dutch",
        "url": "https://www.myolddutch.com/menus/",
        "category": "dutch"
      }
    ]
  },
  {
    "name": "french",
    "places": [
      {
        "name": "balthazar",
        "url": "https://viewthe.menu/2wav",
        "category": "french"
      },
      {
        "name": "bistrot pierre",
        "url": "https://www.bistrotpierre.co.uk/menus/",
        "category": "french"
      },
      {
        "name": "cafe boheme",
        "url": "https://www.cafeboheme.co.uk/#menus",
        "category": "french"
      },
      {
        "name": "cote",
        "url": "https://www.cote.co.uk/restaurant/st-katharine-docks/menus?menucode=a-la-carte",
        "category": "french"
      }
    ]
  },
  {
    "name": "german",
    "places": [
      {
        "name": "gdk (german diner kebab)",
        "url": "https://www.gdk.com/images/misc/d81e71b7e94ee9a078d21662e6705c63.pdf",
        "category": "german"
      },
      {
        "name": "german gymnasium",
        "url": "https://www.germangymnasium.com/wp-content/uploads/sites/75/2023/09/Restaurant-Menu.pdf",
        "category": "german"
      }
    ]
  },
  {
    "name": "greek",
    "places": [
      {
        "name": "the real greek",
        "url": "https://www.therealgreek.com/menu/",
        "category": "greek"
      }
    ]
  },
  {
    "name": "indian",
    "places": [
      {
        "name": "dishoom",
        "url": "https://menu.menuguide.pro/html/dishoom/dishoom.html",
        "category": "indian"
      },
      {
        "name": "mowgli",
        "url": "https://www.mowglistreetfood.com/allergens/",
        "category": "indian"
      }
    ]
  },
  {
    "name": "italian",
    "places": [
      {
        "name": "amalfi",
        "url": "https://www.amalfi.co.uk/menu",
        "category": "italian"
      },
      {
        "name": "ask italian",
        "url": "https://www.askitalian.co.uk/menus/e-menu",
        "category": "italian"
      },
      {
        "name": "bella italia",
        "url": "https://www.bellaitalia.co.uk/menu",
        "category": "italian"
      },
      {
        "name": "coco di mama",
        "url": "https://www.cocodimama.co.uk/menus/instore-menu/pasta",
        "category": "italian"
      },
      {
        "name": "domino's",
        "url": "https://corporate.dominos.co.uk/about-us/our-food/allergens-and-nutrition",
        "category": "italian"
      },
      {
        "name": "gordon ramsay \\- street pizza",
        "url": "https://www.gordonramsayrestaurants.com/assets/1Calorie-Matrices/DUAL-STREET-CALORIE-MATRIX.pdf?srsltid=AfmBOop-eophm3xa36CYYN0bmXXrhXLxHKHmrTtoAmm7SS7FxhWo2i9j",
        "category": "italian"
      },
      {
        "name": "harry's dolce vita",
        "url": "https://harrysdolcevita.com/menu/",
        "category": "italian"
      },
      {
        "name": "little caesars pizza",
        "url": "https://gb.littlecaesars.com/en-gb/nutrition",
        "category": "italian"
      },
      {
        "name": "papa john's",
        "url": "https://www.papajohns.co.uk/static/assets/pdfs/nutritional-information.pdf",
        "category": "italian"
      },
      {
        "name": "pasta evangelist",
        "url": "https://docs.google.com/spreadsheets/d/1I2wXH_PQNO21w4CvaETgOLM7OBJDQCY5b4vq0cK0rEo/pub?output=pdf",
        "category": "italian"
      },
      {
        "name": "pizza express",
        "url": "https://www.pizzaexpress.com/allergens-and-nutritionals",
        "category": "italian"
      },
      {
        "name": "pizza hut",
        "url": "https://www.pizzahut.co.uk/restaurants/food/nutritional-information",
        "category": "italian"
      },
      {
        "name": "pizza pilgrims",
        "url": "https://images.selfridges.com/is/content/selfridges/content/site/pdf/NEW_SELFRIDGES_A3_Pizza_Pilgrims.pdf",
        "category": "italian"
      },
      {
        "name": "prezzo",
        "url": "https://www.prezzo.co.uk/hub/nutritional-and-allergen-information/",
        "category": "italian"
      },
      {
        "name": "protein pizza co",
        "url": "https://proteinpizza.slerp.com/order",
        "category": "italian"
      },
      {
        "name": "rudy's pizza",
        "url": "https://uploads-ssl.webflow.com/60235ab1b46a6761c7554f2e/62862c3b7dab8137cced6943_Leeds.pdf",
        "category": "italian"
      },
      {
        "name": "san carlo cicchetti",
        "url": "https://sancarlo.co.uk/app/uploads/2022/10/Cicchetti-Manc-Oct22-Calories.pdf",
        "category": "italian"
      },
      {
        "name": "vapiano",
        "url": "https://vapiano.com/app/uploads/sites/2/2022/04/Vapiano-Nutritionals.pdf",
        "category": "italian"
      },
      {
        "name": "zizzi",
        "url": "https://www.zizzi.co.uk/propeller/uploads/2024/03/Zizzi-Nutrition-Guide-March-UK-2024-.pdf",
        "category": "italian"
      }
    ]
  },
  {
    "name": "japanese",
    "places": [
      {
        "name": "abokono",
        "url": "https://abokado.com/user/pages/nutrition/NutritionalsAbokadoMar25.pdf",
        "category": "japanese"
      },
      {
        "name": "coco ichibanya",
        "url": "https://ichibanya.uk/assets/Uploads/d64ea89dd3/Allergy_Kcal_menu-list_2025.03.31_amended.pdf",
        "category": "japanese"
      },
      {
        "name": "haku café & izakaya",
        "url": "https://hakucafeizakaya.com/wp-content/themes/haku/img/nutrition-allergen-guide.pdf",
        "category": "japanese"
      },
      {
        "name": "ichikokudo",
        "url": "https://images.zensho.co.jp/materials/ikkokudo/allergen/uk-allergen.pdf",
        "category": "japanese"
      },
      {
        "name": "itsu",
        "url": "https://www.itsu.com/menu/",
        "category": "japanese"
      },
      {
        "name": "ippudo",
        "url": "https://storage.googleapis.com/studio-design-asset-files/projects/JpOL0L4xOQ/s-1x1_ee819ff5-fd2d-4cc6-87ad-684562789974.pdf",
        "category": "japanese"
      },
      {
        "name": "iro sushi",
        "url": "https://www.irosushi.com/",
        "category": "japanese"
      },
      {
        "name": "kokoro",
        "url": "https://www.kokorouk.com/menu",
        "category": "japanese"
      },
      {
        "name": "marugame udon",
        "url": "https://marugame.co.uk/menu/",
        "category": "japanese"
      },
      {
        "name": "nobu",
        "url": "https://www.noburestaurants.com/london-portman-square/menus",
        "category": "japanese"
      },
      {
        "name": "roka",
        "url": "https://www.rokarestaurant.com/en/roka-mayfair-london/menu",
        "category": "japanese"
      },
      {
        "name": "sticks n' sushi",
        "url": "https://a.storyblok.com/f/286316/x/7b068dff71/sns-menu-wip-uk-2024-10-kcal-210x210-100dpi_jpg-high-web.pdf",
        "category": "japanese"
      },
      {
        "name": "sushi dog",
        "url": "https://www.nutritics.com/menu/a2248f3b72/254935",
        "category": "japanese"
      },
      {
        "name": "sushi samba",
        "url": "https://www.sushisamba.com/propeller/uploads/2021/04/2023.06-Sushi-Samba-London-All-Day-Calories-Menu.pdf",
        "category": "japanese"
      },
      {
        "name": "sushi shop",
        "url": "https://www.mysushishop.co.uk/en/all-categories",
        "category": "japanese"
      },
      {
        "name": "tonkotsu",
        "url": "https://tonkotsu.co.uk/wp-content/uploads/2023/09/Tonkotsu-Nutritional-Information-September-2023-1.pdf",
        "category": "japanese"
      },
      {
        "name": "wasabi",
        "url": "https://www.wasabi.uk.com/wp-content/uploads/2025/01/WAS_Nutritional_Guide_090125_V2.pdf",
        "category": "japanese"
      },
      {
        "name": "yakinori",
        "url": "https://www.yakinori.co.uk/how-many-calories-are-in-yakinoris-most-popular-dishes/",
        "category": "japanese"
      },
      {
        "name": "yo sushi",
        "url": "https://yosushi.com/getattachment/1542b7f9-5733-4588-8297-21c764126bad/Allergen-and-Nutritional-Report-December-2022.pdf?lang=en-GB",
        "category": "japanese"
      }
    ]
  },
  {
    "name": "lebanese",
    "places": [
      {
        "name": "comptoir libanais",
        "url": "https://www.comptoirlibanais.com/wp-content/uploads/2024/03/Comptoir_AllergenMenuA4_Feb2024_v07.pdf",
        "category": "lebanese"
      },
      {
        "name": "leon",
        "url": "https://leon.co/menu/all-day/",
        "category": "lebanese"
      },
      {
        "name": "maroush",
        "url": "https://www.maroush.com/wp-content/uploads/2024/10/Maroush-House-Menu-Oct24-Calories.pdf",
        "category": "lebanese"
      },
      {
        "name": "mezza lebanese kitchen",
        "url": "https://www.ordermezza.com/nutritional-info",
        "category": "lebanese"
      }
    ]
  },
  {
    "name": "mexican / south american",
    "places": [
      {
        "name": "barburrito",
        "url": "https://barburrito.co.uk/menu/",
        "category": "mexican / south american"
      },
      {
        "name": "chipotle",
        "url": "https://www.chipotle.co.uk/nutrition-calculator",
        "category": "mexican / south american"
      },
      {
        "name": "chiquito",
        "url": "https://www.chiquito.co.uk/menu",
        "category": "mexican / south american"
      },
      {
        "name": "las iguanas",
        "url": "https://www.iguanas.co.uk/our-menu/",
        "category": "mexican / south american"
      },
      {
        "name": "taco bell",
        "url": "https://www.tacobell.co.uk/nutrition-information/",
        "category": "mexican / south american"
      },
      {
        "name": "tortilla",
        "url": "https://www.tortilla.co.uk/menu/nutrition-and-allergens",
        "category": "mexican / south american"
      },
      {
        "name": "wahaca",
        "url": "https://www.wahaca.co.uk/wp-content/uploads/2024/10/0202_WAH_Main_Estate_Table_Menu_Winter_24_CALORIE_WEB.pdf",
        "category": "mexican / south american"
      },
      {
        "name": "zambrero",
        "url": "https://dph95f73vdxmz.cloudfront.net/uploads/NZ24008_Nutritional_Information_MARCH_2024.pdf",
        "category": "mexican / south american"
      }
    ]
  },
  {
    "name": "pubs",
    "places": [
      {
        "name": "all bar one",
        "url": "https://www.allbarone.co.uk/nutritional-info#/",
        "category": "pubs"
      },
      {
        "name": "aragon house",
        "url": "https://www.aragonhousesw6.com/food-drink/main-menu",
        "category": "pubs"
      },
      {
        "name": "duke of york victoria",
        "url": "https://dukeofyork-victoria.co.uk/menus/",
        "category": "pubs"
      },
      {
        "name": "greene king",
        "url": "https://www.greeneking.co.uk/pubs-restaurants-hotels",
        "category": "pubs"
      },
      {
        "name": "j d wetherspoons",
        "url": "https://allergens.jdwetherspoon.com/?pubId=5505",
        "category": "pubs"
      },
      {
        "name": "the red lion westminster",
        "url": "https://www.redlionwestminster.co.uk/food/main-menu",
        "category": "pubs"
      },
      {
        "name": "the sanctuary house hotel",
        "url": "https://www.sanctuaryhousehotel.co.uk/food/main-menu",
        "category": "pubs"
      }
    ]
  },
  {
    "name": "steak",
    "places": [
      {
        "name": "angus steakhouse",
        "url": "https://koala-configurations.s3.us-east-1.amazonaws.com/public/assets/Nutrition-10-bd685b48-e918-49bc-a190-05723bf04b3f.pdf",
        "category": "steak"
      },
      {
        "name": "bar \\+ block steakhouse",
        "url": "https://www.barandblock.co.uk/en-gb/bar_and_block_spring_summer_core_NGCI_2024_allergy_nutrition_v1.pdf",
        "category": "steak"
      },
      {
        "name": "beefeater",
        "url": "https://www.beefeater.co.uk/en-gb/menus",
        "category": "steak"
      },
      {
        "name": "blacklock",
        "url": "https://viewthe.menu/by8v",
        "category": "steak"
      },
      {
        "name": "gaucho",
        "url": "https://gauchorestaurants.com/wp-content/uploads/2023/03/Gaucho_ALC-Menu_A4_LIV_0423.pdf",
        "category": "steak"
      },
      {
        "name": "hawksmoor",
        "url": "https://quandoo-assets-partner.s3-eu-west-1.amazonaws.com/partner/uploads/9f35331e-178d-4b4d-9912-42d9ac200fb2/MD-document-d85c95ba-b9d3-47e9-8fc7-f981838e4ca3.pdf",
        "category": "steak"
      },
      {
        "name": "flat iron",
        "url": "https://flatironsteak.co.uk/calories/",
        "category": "steak"
      },
      {
        "name": "steak and company",
        "url": "https://system.ifoodi.com/console/qrmenu/579/347",
        "category": "steak"
      }
    ]
  },
  {
    "name": "swedish",
    "places": [
      {
        "name": "ikea",
        "url": "https://www.ikea.com/gb/en/food/",
        "category": "swedish"
      }
    ]
  },
  {
    "name": "thai",
    "places": [
      {
        "name": "busaba",
        "url": "https://www.busaba.com/menu/food",
        "category": "thai"
      },
      {
        "name": "chaophraya",
        "url": "https://chaophraya.co.uk/fileadmin/Menus/Chaophraya_A_La_Carte_April_22_NewcastleLeedsBirmingham.pdf",
        "category": "thai"
      },
      {
        "name": "camile thai",
        "url": "https://ams3.digitaloceanspaces.com/camile-production/documents/a4-pdf-macros-menu-jan25-11.pdf",
        "category": "thai"
      },
      {
        "name": "giggling squid",
        "url": "https://www.gigglingsquid.com/menu/",
        "category": "thai"
      },
      {
        "name": "rosa's thai",
        "url": "https://rosasthai.com/menus",
        "category": "thai"
      },
      {
        "name": "thai express",
        "url": "https://thaiexpress.co.uk/wp-content/uploads/2023/09/20180202-NUTRITIONAL-INFO-ENG_.pdf",
        "category": "thai"
      },
      {
        "name": "thai khun",
        "url": "https://www.thaikhun.co.uk/fileadmin/TK_Menus/TK_A3_Bath_JUL22_V4.pdf",
        "category": "thai"
      },
      {
        "name": "thaiphoon",
        "url": "https://thaiphoon.co.uk/menus/",
        "category": "thai"
      }
    ]
  },
  {
    "name": "vietnamese",
    "places": [
      {
        "name": "hop vietnamese",
        "url": "https://www.hopvietnamese.com/menu",
        "category": "vietnamese"
      },
      {
        "name": "pho",
        "url": "https://content.phocafe.co.uk/wp-content/uploads/2025/01/Pho-Nutritional-Guidelines-2024_web.pdf",
        "category": "vietnamese"
      }
    ]
  }
];

export const parsePlacesData = (): Category[] => categories;

export const getAllPlaces = (): Place[] => {
  return categories.flatMap(category => category.places);
};

export const getRandomPlace = (selectedCategories?: string[]): Place => {
  let places: Place[];

  if (selectedCategories && selectedCategories.length > 0) {
    places = categories
      .filter(cat => selectedCategories.includes(cat.name))
      .flatMap(cat => cat.places);
  } else {
    places = getAllPlaces();
  }

  return places[Math.floor(Math.random() * places.length)];
};

export const getCategoryNames = (): string[] => {
  return categories.map(cat => cat.name);
};
